# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebasePushNotifiation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebasePushNotifiation
pod 'Firebase/Messaging'
  target 'FirebasePushNotifiationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebasePushNotifiationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
